name: Check androidLint & unitTest

on:
  workflow_dispatch:
  pull_request:

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
  check-android-lint:
    runs-on: ubuntu-latest
    needs: [set-up]
    steps:
      - name: Run android lint
        run: ./gradlew lintDebug
  run-unit-test:
    runs-on: ubuntu-latest
    needs: [set-up]
    steps:
      - name: Run unit test
        run: ./gradlew testDebugUnitTest --stacktrace
